### ISSUE TITLE
NameError: global name 'gzip' is not defined

### ISSUE THREAD

**Issue by sung** [lpantano/seqcluster#11]
Hi,

I followed the instruction manual, but could not manage to run 'seqcluster':
[ssg29@login-sand1 ~]$ which seqcluster
~/Install/seqcluster/linuxbrew/bin/seqcluster
[ssg29@login-sand1 ~]$ seqcluster
Traceback (most recent call last):
  File "/home/ssg29/Install/seqcluster/linuxbrew/bin/seqcluster", line 4, in <module>
    from seqcluster.command_line import main
  File "/home/ssg29/Install/seqcluster/anaconda/lib/python2.7/site-packages/seqcluster/command_line.py", line 4, in <module>
    from prepare_data import prepare
  File "/home/ssg29/Install/seqcluster/anaconda/lib/python2.7/site-packages/seqcluster/prepare_data.py", line 8, in <module>
    from libs.classes import sequence_unique
  File "/home/ssg29/Install/seqcluster/anaconda/lib/python2.7/site-packages/seqcluster/libs/classes.py", line 6, in <module>
    import numpy as np
  File "/home/ssg29/.local/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/ssg29/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/ssg29/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/ssg29/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/ssg29/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: /home/ssg29/.local/lib/python2.7/site-packages/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS2_AsASCIIString

It seems anaconda tries to pick up local numpy package as shown below.

If I manually export PYTHONPATH like:
PYTHONPATH=$HOME/Install/seqcluster/anaconda/lib/python2.7/site-packages:$PYTHONPATH

Then, seqcluster seems to work:
[ssg29@login-sand1 ~]$ seqcluster
use ['stats', 'collapse', 'prepare', 'predict', 'cluster', 'explore', 'report']

I wanted to use 'collapse', but with no luck:

[ssg29@login-sand1 ~]$ seqcluster collapse -f ~/results/SLX-9176.Homo_sapiens.v1/Trim/NEBsmRNA01/SLX-9176.NEBsmRNA01.C7TWVANXX.s_6.r_1_trimmed.fq.gz -o ~/results/SLX-9176.Homo_sapiens.v1/Trim/NEBsmRNA01/SLX-9176.NEBsmRNA01.C7TWVANXX.s_6.r_1_trimmed.collapsed
07/30/2015 03:31:13 PM INFO: Run collapse Traceback (most recent call last):
  File "/home/ssg29/Install/seqcluster/linuxbrew/bin/seqcluster", line 6, in <module>
    sys.exit(main())
  File "/home/ssg29/Install/seqcluster/anaconda/lib/python2.7/site-packages/seqcluster/command_line.py", line 40, in main
    collapse_fastq(kwargs["args"])
  File "/home/ssg29/Install/seqcluster/anaconda/lib/python2.7/site-packages/seqcluster/collapse.py", line 14, in collapse_fastq
    seqs = collapse(args.fastq)
  File "/home/ssg29/Install/seqcluster/anaconda/lib/python2.7/site-packages/seqcluster/libs/fastq.py", line 10, in collapse
    with open_fastq(in_file) as handle:
  File "/home/ssg29/Install/seqcluster/anaconda/lib/python2.7/site-packages/seqcluster/libs/fastq.py", line 30, in open_fastq
    return gzip.open(in_file, 'rb')
NameError: global name 'gzip' is not defined

Any idea?

Sung

**Comment by lpantano** [comment]
thanks so much!

please let me know if the devel version doesn't work!

**Comment by lpantano** [comment]
@sung, I will update the conda binary this afternoon. In case you want to try first with the code in github.

thanks for your patient!

**Comment by lpantano** [comment]
Hi @sung, conda binary is updated.

please let me know if the issue got away.

thanks!
