### ISSUE TITLE
Collapse

### ISSUE THREAD

**Issue by filicado** [lpantano/seqcluster#13]
I'm running seqcluster inside the provided docker container (https://hub.docker.com/r/bcbio/bcbio/)

When running the collapse script I encounter this error:

['collapse', '-f', '/seqdata/readscleaned/33_S1_body.fastq.clean', '-o', '/seqdata/collapsed']
INFO Run collapse
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/bin/seqcluster", line 9, in <module>
    load_entry_point('seqcluster==1.1.14', 'console_scripts', 'seqcluster')()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/seqcluster/command_line.py", line 49, in main
    collapse_fastq(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/seqcluster/collapse.py", line 13, in collapse_fastq
    seqs = collapse(args.fastq)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/seqcluster/libs/fastq.py", line 11, in collapse
    with open_fastq(in_file) as handle:
AttributeError: __exit__

Any ideas what the problem could be?
Thanks

**Comment by filicado** [comment]
sorry stupid issue they need to have a fastq extension

**Comment by lpantano** [comment]
thanks for looking into that! i will add a proper handler there!
