### ISSUE TITLE
problem with "seqcluster report" command

### ISSUE THREAD

**Issue by AlexandraBomane** [lpantano/seqcluster#20]
Hello lpantano,

I had the following error launching the command "seqcluster report -j seqcluster.json -o Report -r ref.fasta" : 

.................
INFO locus bigger > 500 nt, skipping: [[1108, u'1', 207324614, 207326831, u'+', 35]]
INFO locus bigger > 500 nt, skipping: [[3617, u'11', 62882013, 62882997, u'+', 11]]
INFO locus bigger > 500 nt, skipping: [[7088, u'15', 40038287, 40038885, u'-', 19]]
INFO locus bigger > 500 nt, skipping: [[16701, u'6', 26538052, 26687281, u'+', 659]]
['report', '-j', 'ClusteringStep/seqcluster.json', '-o', 'ReportStep', '-r', '/root/Homo_sapiens.GRCh38.dna.toplevel.cleaned.fasta']
Traceback (most recent call last):
  File "/usr/local/bin/seqcluster", line 9, in <module>
    load_entry_point('seqcluster==1.2.3a0', 'console_scripts', 'seqcluster')()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/seqcluster/command_line.py", line 31, in main
    report(kwargs["args"])
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/seqcluster/create_report.py", line 32, in report
    data = make_profile(data, out_dir, args)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/seqcluster/libs/report.py", line 66, in make_profile
    data[0][c]['precursor'].update(run_rnafold(data[0][c]['precursor']['seq']))
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/seqcluster/function/rnafold.py", line 12, in run_rnafold
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long

I don't understand how this error was triggered. How can I avoid this problem ?

Thanks,
Alexandra

**Comment by lpantano** [comment]
Hi,

I just pushed a fix for that, hoping is that. Can you update to development? There should be a command `seqcluster_install --upgrade` that should install from github.

Let me know if that works.

**Comment by AlexandraBomane** [comment]
Hi,

I tested your modification and it works very well ! :)

Thanks,
Alexandra
