### ISSUE TITLE
Permission denied during collapse step

### ISSUE THREAD

**Issue by AlexandraBomane** [lpantano/seqcluster#22]
Hi Lorena !

I found a new issue with seqcluster using the following command line : 
/usr/local/bin/seqcluster collapse -f file.fastq -o out_collapse

Here the error message : 

Traceback (most recent call last):
  File "/usr/local/bin/seqcluster", line 9, in <module>
    load_entry_point('seqcluster==1.2.4a0', 'console_scripts', 'seqcluster')()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 549, in load_entry_point
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2542, in load_entry_point
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2202, in load
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 2208, in resolve
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/seqcluster/command_line.py", line 6, in <module>
    from create_report import report
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/seqcluster/create_report.py", line 7, in <module>
    _set_matplotlib_default_backend()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 143, in _set_matplotlib_default_backend
    out_file.write(line)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 75, in file_transaction
    _move_tmp_files(safe, orig)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 92, in _move_tmp_files
    _move_file_with_sizecheck(safe, orig)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 117, in _move_file_with_sizecheck
    shutil.move(tx_file, final_file)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: u'/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc'

Do you know what could be the problem?

Thanks in advance,
Alexandra

**Comment by lpantano** [comment]
Hi,

sorry for the issue. 
Can you tell me if you have permission to write there?

what do you see if you do:

ll /usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/matplotlib/mpl-data

**Comment by lpantano** [comment]
Hi Alexandra,

did you solve this problem? I am trying to wrap my mind around, and still didn't find the cause. Maybe another solution is trying to reinstall matplotlib with conda. 

I will remove this step from the code in the future, so hopefully this won't be an issue anymore.

**Comment by cbouyio** [comment]
Hi Lorena,

Thanks for your answer!
Let me introduce myself, this is Costas a computational biologist that works with Alexandra on the project that we use SeqCluster.
Actually I do not use a (ana)conda installation myself and we do not use SeqCluster through the bcbio-nextgen directly. We use a docker image made by an institute here in Paris so we do not have full control of it.
We do not have a native installation of bcbio-nextgen. As I am not big fun of (ana)conda (and any non-native installations of python packages for that matter) is there any way to install bcbio-nextgen ourselves? If this is possible than I can pull together our own docker image and do not depend on docker images of others.

At any case I am available to provide any kind of help you would like to resolve the issue, I am an experienced python developer, so please do not hesitate to contact me for any issue.

So lets start from the bcbio-nextgen issue and take it from there.

Best regards,
Costas

**Comment by cbouyio** [comment]
Hi again,
I just show that you have an official docker release for bcbio-nextgen available on the project's website.
If it is "conda-free", and it does not reproduce the issue we mentioned, I am more inclined to use it directly.

Best regards,
Costas

**Comment by lpantano** [comment]
Hi Costas!
sorry for the issues,

it won’t be conda free, because we based all our dependency on that, but it should be stable and you should be able to use it directly. Conda is only used if you want to update, but in that case you always can just get the new docker version instead of updating the software by yourself.

Can you try it anyways and let me know?

thanks!
