### ISSUE TITLE
issue in seqcluster collapser

### ISSUE THREAD

**Issue by YangZituo** [lpantano/seqcluster#24]
Hi, 
I have already installed the bcbio and run the cutadapt. After i run the collapse, it cannot work.

[ns_phd06@tll-rv1 bin]$ seqcluster collapse -f /data/GenhuaLab/zituo/BCBIOresults/sm0h_1.fastq -o /data/GenhuaLab/zituo/BCBIOresults/sm0h_1.collapser.fastq

Traceback (most recent call last):
  File "./seqcluster", line 11, in <module>
    load_entry_point('seqcluster==1.2.4a0', 'console_scripts', 'seqcluster')()
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/seqcluster/command_line.py", line 5, in <module>
    from make_clusters import cluster
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/seqcluster/make_clusters.py", line 11, in <module>
    import pybedtools
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/__init__.py", line 12, in <module>
    from . import contrib
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/contrib/__init__.py", line 3, in <module>
    from . import venn_maker
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/contrib/venn_maker.py", line 12, in <module>
    from pybedtools import helpers
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/helpers.py", line 13, in <module>
    import pysam
  File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory

Please help me, Thank!! @lpantano

**Comment by lpantano** [comment]
Hi,

Can you look at this to see if that helps:

https://github.com/chapmanb/bcbio-nextgen/issues/1905 <https://github.com/chapmanb/bcbio-nextgen/issues/1905>


Let me know!

**Comment by lpantano** [comment]
Hi,

let me know if this is still a problem. Feel free to re-open. I hope it got solved!
