### ISSUE TITLE
An error occurred when running the program

### ISSUE THREAD

**Issue by charles-xue** [lpantano/seqcluster#56]
Hello, I want to use this tool for miRNA analysis. It has been installed, but the following error was reported when running the demo data. What should I do to solve this problem?

`[2023-11-08T02:44Z] System YAML configuration: /home/wayenbio/bcbio/galaxy/bcbio_system.yaml.
[2023-11-08T02:44Z] Locale set to C.UTF-8.
[2023-11-08T02:44Z] Resource requests: atropos, picard; memory: 4.00, 4.00; cores: 16, 16
[2023-11-08T02:44Z] Configuring 1 jobs to run, using 1 cores each with 4.00g of memory reserved for each job
[2023-11-08T02:44Z] Timing: organize samples
[2023-11-08T02:44Z] multiprocessing: organize_samples
[2023-11-08T02:44Z] Using input YAML configuration: /home/wayenbio/rnaseq-seqc/mirqc_bcbio/config/mirqc_bcbio.yaml
[2023-11-08T02:44Z] Checking sample YAML configuration: /home/wayenbio/rnaseq-seqc/mirqc_bcbio/config/mirqc_bcbio.yaml
Traceback (most recent call last):
  File "/home/wayenbio/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/home/wayenbio/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 332, in smallrnaseqpipeline
    samples = rnaseq_prep_samples(config, run_info_yaml, parallel, dirs, samples)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/main.py", line 467, in rnaseq_prep_samples
    [x[0]["description"] for x in samples]]])
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/distributed/multitasks.py", line 459, in organize_samples
    return run_info.organize(*args)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/run_info.py", line 81, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/run_info.py", line 177, in add_reference_resources
    data["dirs"]["galaxy"], data)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/genome.py", line 233, in get_refs
    galaxy_config, data)
  File "/home/wayenbio/bcbio/anaconda/lib/python3.7/site-packages/bcbio/pipeline/genome.py", line 180, in _get_ref_from_galaxy_loc
    (genome_build, os.path.normpath(loc_file)))
ValueError: Did not find genome build hg19 in bcbio installation: /home/wayenbio/bcbio/galaxy/tool-data/sam_fa_indices.loc
`

**Comment by lpantano** [comment]
Hi,
can you let me know what was the command you were running? how did you install seqcluster? and the version you are using? Thanks

**Comment by charles-xue** [comment]
I installed bcbio and downloaded the miRNA data from it following the guide at https://seqcluster.readthedocs.io/ page.
template.yaml
`upload:
  dir: upload
details:
  - analysis: smallRNA-seq
    algorithm:
      aligner: star
      adapters: ["TGGAATTCTCGGGTGC"]
      species: hsa
    description: miRQCa
    genome_build: hg19`
![image](https://github.com/lpantano/seqcluster/assets/39455417/e9e42fd1-4f13-4ee3-88c2-7476db09d206)
and then run it
![image](https://github.com/lpantano/seqcluster/assets/39455417/c6041222-7a0a-4306-9538-eae9e41ab10f)
But the error message described above appeared. I saw that the error message said that the genome-related files were not found. I guessed that this should be a problem that occurred during the installation, but I don’t know how to solve it. Can you Give some tips?
![image](https://github.com/lpantano/seqcluster/assets/39455417/c4fe9f97-6941-4c5f-8a05-3e0d901d1dd4)

**Comment by lpantano** [comment]
If you are using bcbio maybe something else is missing. Here there is more information if you want to run bcbio: https://bcbio-nextgen.readthedocs.io/en/latest/contents/small_rnaseq.html.  And here to install data: https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#install-data.
If you want to run only seqcluster then I can help you with that in a different way.
You can use nf-core smrnaseq as well, it is a little different but it will get you seqcluster running.https://nf-co.re/smrnaseq/2.2.3

**Comment by charles-xue** [comment]
Yes, I found the relevant content about smallRNA analysis in the nf-core page through the information on your seqcluster page. I am trying to install this kit to perform the pipeline of miRNA analysis. I hope everything goes well. Also thanks for your answer

**Comment by charles-xue** [comment]
I installed the program correctly according to the instructions in the documentation, but problems always occur when I run real data. I searched online and it seems that this problem is quite common, but I still can't find a solution. Can you give me an answer?

samplesheet.csv
![image](https://github.com/lpantano/seqcluster/assets/39455417/37744c33-349e-4017-a214-31f497ae358b)
![image](https://github.com/lpantano/seqcluster/assets/39455417/4b275c4c-03f7-4431-8dd6-8f18cf9c5873)



Execution cancelled -- Finishing pending tasks before exit
-[nf-core/smrnaseq] Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)'

Caused by:
  Process `NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK (samplesheet.csv)` terminated with an error exit status (1)

Command executed:

  check_samplesheet.py \
      samplesheet.csv \
      samplesheet.valid.csv

  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SMRNASEQ:SMRNASEQ:INPUT_CHECK:SAMPLESHEET_CHECK":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  1

Command output:
  ERROR: Please check samplesheet -> ERROR: Please check samplesheet header. Missing columns: 'sample'

Command error:
  ERROR: Please check samplesheet -> ERROR: Please check samplesheet header. Missing columns: 'sample'

Work dir:
  /home/wayenseq/work/02/74870224d805ba01993675ec4fce19

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
